USE [master]
GO

/****** Object:  Database [BlogerDb]    Script Date: 8/21/2020 11:24:13 PM ******/
CREATE DATABASE [BlogerDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogerDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BlogerDb.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BlogerDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BlogerDb_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BlogerDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlogerDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlogerDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlogerDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlogerDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlogerDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlogerDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlogerDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BlogerDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlogerDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlogerDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlogerDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlogerDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlogerDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlogerDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlogerDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlogerDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BlogerDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlogerDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlogerDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlogerDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlogerDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlogerDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BlogerDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlogerDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlogerDb] SET  MULTI_USER 
GO

ALTER DATABASE [BlogerDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlogerDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlogerDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlogerDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BlogerDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlogerDb] SET  READ_WRITE 
GO

